gestion_boutiques:
    resource: "@GestionBoutiquesBundle/Resources/config/routing.yml"
    prefix:   /boutique

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /test

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
