calendrier_medecins:
    resource: "@CalendrierMedecinsBundle/Resources/config/routing.yml"
    prefix:   /examen1

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"